export const MUTATIONS = {
    SET_HORSES: 'SET_HORSES',
    ADD_PROGRAM: 'ADD_PROGRAM',
    ADD_RESULTS: 'ADD_RESULTS',
    SET_RACE_RUNNING: 'SET_RACE_RUNNING',
    SET_INTERVAL_ID: 'SET_INTERVAL_ID',
    SET_SELECTED_HORSES: 'SET_SELECTED_HORSES',
    START_RACE: 'START_RACE',
    UPDATE_HORSE_POSITION: 'UPDATE_HORSE_POSITION',
    PAUSE_RACE: 'PAUSE_RACE',
    NEXT_LAP: 'NEXT_LAP',
    DECREASE_CONDITIONS: 'DECREASE_CONDITIONS',
    INCREASE_CONDITIONS: 'INCREASE_CONDITIONS',
    UPDATE_HORSE_CONDITIONS: 'UPDATE_HORSE_CONDITIONS'
  };
  
  export const ACTIONS = {
    GENERATE_HORSES: 'generateHorses',
    GENERATE_PROGRAM: 'generateProgram',
    START_RACE: 'startRace',
    RUN_RACE: 'runRace',
    PAUSE_RACE: 'pauseRace',
    RESET_RESULTS: 'resetResults'
  };
  